---
- name: Create traefik default network
  community.docker.docker_network:
    name: traefik_net

- name: Create pretalx container network
  community.docker.docker_network:
    name: pretalx_net
  register: pretalx_net_info

- name: Print network info
  ansible.builtin.debug:
    msg: "{{ pretalx_net_info.network.IPAM.Config[0].Subnet }}"

- name: Create wordpress container network
  community.docker.docker_network:
    name: wordpress_net
  register: wordpress_net_info

- name: Print network info
  ansible.builtin.debug:
    msg: "{{ wordpress_net_info.network.IPAM.Config[0].Subnet }}"

- name: Create traefik container
  community.docker.docker_container:
    name: traefik
    image: "{{ devday_traefik_image|default('traefik') }}:{{ devday_traefik_image_tag|default('latest') }}"
    ports:
      - "80:80"  # Optional: HTTP
      - "443:443"  # Optional: HTTPS
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--ping.entryPoint=websecure"
      - "--log.level={{ traefik_log_level|default('INFO') }}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesResolvers.myresolver.acme.email={{ devday_acme_email }}"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
      - "--certificatesResolvers.myresolver.acme.keyType=EC384"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:z"
      - "/var/lib/traefik:/acme"
    networks:
      - name: pretalx_net
      - name: traefik_net
      - name: wordpress_net
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik_dashboard.rule: "Host(`{{ devday_web_fqdn }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard/`))"
      traefik.http.routers.traefik_dashboard.service: "api@internal"
      traefik.http.routers.traefik_dashboard.middlewares: "auth-dashboard"
      traefik.http.middlewares.auth-dashboard.basicauth.users: "{{ devday_traefik_dashboard_user }}:{{ devday_traefik_dashboard_password_hash }}"
      traefik.http.routers.redirect.rule: >-
        Host(`{{ devday_website_short_name }}`) || 
        Host(`{{ devday_web_fqdn }}`)
      traefik.http.routers.redirect.middlewares: "redirect"
      traefik.http.middlewares.redirect.redirectregex.regex: ".*"
      traefik.http.middlewares.redirect.redirectregex.replacement: "https://www.devday.de/"
    restart_policy: unless-stopped
