galaxy_info:
  author: Jan Dittberner
  description: PostgreSQL setup for Dev Day applications
  company: T-Systems Multimedia Solutions GmbH

  issue_tracker_url: https://github.com/devdaydresden/devday_ansible/issues
  license: GPL-3.0-or-later

  min_ansible_version: 2.1

  platforms:
  - name: Debian
    versions:
    - all

  galaxy_tags: []

dependencies: []
