---

- name: Log into ghcr.io
  community.docker.docker_login:
    registry_url: "ghcr.io"
    username: "{{ ghcr_registry_user }}"
    password: "{{ ghcr_registry_access_token }}"
    reauthorize: true

- name: Website nginx container
  community.docker.docker_container:
    name: devday-static-website
    image: "{{ devday_static_website_image|default('ghcr.io/devdaydresden/devday_static_website') }}:{{ devday_static_website_version|default('latest') }}"
    pull: always
    platform: linux/amd64
    restart_policy: unless-stopped
    networks:
      - name: traefik_net
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_net
      traefik.http.routers.static-website.service: static-website
      traefik.http.routers.static-website.rule: "Host(`{{ devday_website_fqdn|default('localhost') }}`)"
      traefik.http.services.static-website.loadbalancer.server.port: "80"
      traefik.http.services.static-website.loadbalancer.passhostheader: "true"
