---
- name: Create directory for devday
  ansible.builtin.file:
    path: /var/lib/devday
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create Redis container
  community.docker.docker_container:
    name: redis
    image: "redis:{{ devday_redis_version|default('latest') }}"
    restart_policy: unless-stopped
    networks:
      - name: pretalx_net
    volumes:
      - redis-data:/data

- name: Create PreTalx web container
  community.docker.docker_container:
    name: pretalx-web
    image: "{{ devday_pretalx_imape|default('ghcr.io/devdaydresden/pretalx-docker') }}:{{ devday_pretalx_version|default('latest') }}"
    entrypoint: gunicorn
    command:
      - "pretalx.wsgi"
      - "--name"
      - "pretalx"
      - "--workers"
      - "4"
      - "--max-requests"
      - "1200"
      - "--max-requests-jitter"
      - "50"
      - "--log-level=info"
      - "--bind=0.0.0.0:8080"
    expose:
      - 8080/tcp
    restart_policy: unless-stopped
    env:
      PRETALX_DATA_DIR: /data
      PRETALX_FILESYSTEM_MEDIA: /public/media
      PRETALX_FILESYSTEM_STATIC: /public/static
      PRETALX_SITE_URL: "{{ devday_pretalx_site_url }}"
      PRETALX_DB_TYPE: postgresql
      PRETALX_DB_NAME: "{{ devday_pretalx_db_name|default('pretalx') }}"
      PRETALX_DB_USER: "{{ devday_pretalx_db_user|default('pretalx') }}"
      PRETALX_DB_PASS: "{{ devday_pretalx_db_password|default('pretalx') }}"
      PRETALX_DB_HOST: pgsql
      PRETALX_DB_PORT: "{{ devday_pretalx_db_port|default(omit) }}"
      PRETALX_MAIL_FROM: "{{ devday_pretalx_mail_from }}"
      PRETALX_MAIL_HOST: "{{ devday_pretalx_mail_host|default('mail') }}"
      PRETALX_MAIL_PORT: "{{ devday_pretalx_mail_port|default(25) }}"
      PRETALX_MAIL_USER: "{{ devday_pretalx_mail_user|default(omit) }}"
      PRETALX_MAIL_PASSWORD: "{{ devday_pretalx_mail_password|default(omit) }}"
      PRETALX_MAIL_TLS: "{{ devday_pretalx_mail_tls|default(omit) }}"
      PRETALX_CELERY_BACKEND: redis://redis/1
      PRETALX_CELERY_BROKER: redis://redis/2
      PRETALX_REDIS: redis://redis/3
      PRETALX_REDIS_SESSIONS: "True"
      PRETALX_LOGGING_EMAIL: "{{ devday_pretalx_logging_email|default(omit) }}"
      PRETALX_LANGUAGE_CODE: de
      PRETALX_TIME_ZONE: Europe/Berlin
    networks:
      - name: pretalx_net
    volumes:
      - pretalx-data:/data
      - pretalx-public:/public
    labels:
      traefik.enable: "true"
      traefik.docker.network: pretalx_net
      traefik.http.routers.pretalx-web.service: pretalx-web
      traefik.http.routers.pretalx-web.rule: "Host(`{{ devday_pretalx_site_fqdn|default('localhost') }}`)"
      traefik.http.routers.pretalx-web.tls: "true"
      traefik.http.routers.pretalx-web.tls.domains: "{{ devday_pretalx_site_fqdn|default('localhost') }}"
      traefik.http.routers.pretalx-web.tls.certResolver: "myresolver"
      traefik.http.services.pretalx-web.loadbalancer.server.port: "8080"
      traefik.http.services.pretalx-web.loadbalancer.passhostheader: "true"

- name: create PreTalx celery worker container
  community.docker.docker_container:
    name: pretalx-celery
    image: "{{ devday_pretalx_imape|default('ghcr.io/devdaydresden/pretalx-docker') }}:{{ devday_pretalx_version|default('latest') }}"
    command: taskworker
    restart_policy: unless-stopped
    env:
      PRETALX_DATA_DIR: /data
      PRETALX_FILESYSTEM_MEDIA: /public/media
      PRETALX_FILESYSTEM_STATIC: /public/static
      PRETALX_SITE_URL: "{{ devday_pretalx_site_url }}"
      PRETALX_DB_TYPE: postgresql
      PRETALX_DB_NAME: "{{ devday_pretalx_db_name|default('pretalx') }}"
      PRETALX_DB_USER: "{{ devday_pretalx_db_user|default('pretalx') }}"
      PRETALX_DB_PASS: "{{ devday_pretalx_db_password|default('pretalx') }}"
      PRETALX_DB_HOST: pgsql
      PRETALX_DB_PORT: "{{ devday_pretalx_db_port|default(omit) }}"
      PRETALX_MAIL_FROM: "{{ devday_pretalx_mail_from }}"
      PRETALX_MAIL_HOST: "{{ devday_pretalx_mail_host|default('mail') }}"
      PRETALX_MAIL_PORT: "{{ devday_pretalx_mail_port|default(25) }}"
      PRETALX_MAIL_USER: "{{ devday_pretalx_mail_user|default(omit) }}"
      PRETALX_MAIL_PASSWORD: "{{ devday_pretalx_mail_password|default(omit) }}"
      PRETALX_MAIL_TLS: "{{ devday_pretalx_mail_tls|default(omit) }}"
      PRETALX_CELERY_BACKEND: redis://redis/1
      PRETALX_CELERY_BROKER: redis://redis/2
      PRETALX_REDIS: redis://redis/3
      PRETALX_REDIS_SESSIONS: "True"
      PRETALX_LOGGING_EMAIL: "{{ devday_pretalx_logging_email|default(omit) }}"
      PRETALX_LANGUAGE_CODE: de
      PRETALX_TIME_ZONE: Europe/Berlin
    volumes:
      - pretalx-data:/data
      - pretalx-public:/public
    networks:
      - name: pretalx_net

- name: Create nginx container to serve static files
  community.docker.docker_container:
    name: pretalx-static
    image: docker.io/library/nginx
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: pretalx_net
      traefik.http.routers.pretalx-static.service: pretalx-static
      traefik.http.routers.pretalx-static.rule: "Host(`{{ devday_pretalx_site_fqdn|default('localhost') }}`) && (PathPrefix(`/media`) || PathPrefix(`/static`))"
      traefik.http.routers.pretalx-static.tls: "true"
      traefik.http.routers.pretalx-static.tls.domains: "{{ devday_pretalx_site_fqdn|default('localhost') }}"
      traefik.http.routers.pretalx-static.tls.certResolver: "myresolver"
      traefik.http.services.pretalx-static.loadbalancer.server.port: "80"
      traefik.http.services.pretalx-static.loadbalancer.passhostheader: "true"
    volumes:
      - pretalx-public:/usr/share/nginx/html

# setup outgoing mail relay
- name: create Postfix mail relay container
  community.docker.docker_container:
    name: mail
    image: "panubo/postfix:{{ devday_postfix_version }}"
    env:
      MAILNAME: "{{ devday_mailname }}"
      BOUNCE_ADDRESS: "{{ devday_pretalx_mail_from }}"
    volumes:
      - postfix_spool:/var/spool/postfix:rw
    networks:
      - name: pretalx_net
