galaxy_info:
  author: Jan Dittberner, Sebastian Breit
  description: Traefik setup for Dev Day
  company: Telekom MMS GmbH

  issue_tracker_url: https://github.com/devdaydresden/devday_ansible/issues
  license: GPL-3.0-or-later

  min_ansible_version: 2.1


  platforms:
  - name: Debian
    versions:
    - all

  galaxy_tags: []

dependencies: []
