---
- name: setup users

  hosts: all
  remote_user: root

  tasks:
    - name: make sure sudo is installed
      ansible.builtin.package:
        name: sudo
        state: present
    - name: create group
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.uid }}"
      loop: "{{ admin_users }}"
    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: "{{ item.name }}"
        uid: "{{ item.uid }}"
        system: "{{ item.system|default(False) }}"
        password: "{{ item.password|default('') }}"
        update_password: on_create
        groups:
          - sudo
      loop: "{{ admin_users }}"
    - name: setup ssh key
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_key }}"
      loop: "{{ admin_users }}"
