---
- name: Harden system

  hosts: all
  become: true

  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
    os_auth_pw_max_age: 99999

  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
