---
- name: "Install pretalx"
  hosts: all
  become: yes

  roles:
    - devday.traefik
    - devday.postgresql
    - devday.mariadb
    - devday.pretalx
    - devday.wordpress
    - devday.static_website